theme = "varua"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "read-only-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
diagnostics = ["warning", "error"]
workspace-diagnostics = ["warning", "error"]

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

# KEYBINDS
[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
 
[keys.normal.space.s]
o = ":config-reload"

[keys.normal.space]
w = ":write"
o = ["add_newline_below"]
O = ["add_newline_above"]

[keys.normal.space.space]
w = ":write-quit"
